#!/bin/sh




#### DA results on the visDA datast
CUDA_VISIBLE_DEVICES=0,1,2 python main.py --no_uniform --category_mean --saving --source_weight instance --filter_type all  --transform_type mme --mu 7 --max_iters 100000 --pre_epoch 1   --lp_labeled st --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center st --thr 0.0 --pseudo_type hard  --init_center st --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --patience 15 --net resnet34 --source train --target validation --method cc_da --batchsize 64  --ratio_t 0.5   --save_dir davisda --dataset visDA --datapath /data/vdd/yabin/data






##############3
#####ssda #######
################3   ### NOTE that all the SSDA results are achieved without the source data selection. However, better results are expected with the source selection.
CUDA_VISIBLE_DEVICES=7,6,5,4 python main.py --num_labeled 1 --base_lr 0.01  --max_iters 10000  --filter_type all --lp_labeled st --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center st --thr 0.0 --pseudo_type hard  --init_center st --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --patience 15 --net vgg --source Real --target Clipart --method cc --batchsize 64  --ratio_t 0.5   --save_dir vgghome --dataset OfficeHome --datapath /data/vdd/yabin/data/OfficeHome

CUDA_VISIBLE_DEVICES=7,6,5,4 python main.py --num_labeled 1 --base_lr 0.01 --max_iters 10000  --filter_type all --lp_labeled st --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center st --thr 0.0 --pseudo_type hard  --init_center st --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --patience 15 --net vgg --source Real --target Product --method cc --batchsize 64  --ratio_t 0.5   --save_dir vgghome --dataset OfficeHome --datapath /data/vdd/yabin/data/OfficeHome

CUDA_VISIBLE_DEVICES=7,6,5,4 python main.py --num_labeled 1 --base_lr 0.01 --max_iters 10000  --filter_type all --lp_labeled st --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center st --thr 0.0 --pseudo_type hard  --init_center st --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --patience 15 --net vgg --source Real --target Art --method cc --batchsize 64  --ratio_t 0.5   --save_dir vgghome --dataset OfficeHome --datapath /data/vdd/yabin/data/OfficeHome

CUDA_VISIBLE_DEVICES=7,6,5,4 python main.py --num_labeled 1 --base_lr 0.01 --max_iters 10000  --filter_type all --lp_labeled st --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center st --thr 0.0 --pseudo_type hard  --init_center st --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --patience 15 --net vgg --source Product --target Real --method cc --batchsize 64  --ratio_t 0.5   --save_dir vgghome --dataset OfficeHome --datapath /data/vdd/yabin/data/OfficeHome

CUDA_VISIBLE_DEVICES=7,6,5,4 python main.py --num_labeled 1 --base_lr 0.01 --max_iters 10000  --filter_type all --lp_labeled st --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center st --thr 0.0 --pseudo_type hard  --init_center st --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --patience 15 --net vgg --source Product --target Clipart --method cc --batchsize 64  --ratio_t 0.5   --save_dir vgghome --dataset OfficeHome --datapath /data/vdd/yabin/data/OfficeHome

CUDA_VISIBLE_DEVICES=7,6,5,4 python main.py --num_labeled 1 --base_lr 0.01 --max_iters 10000  --filter_type all --lp_labeled st --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center st --thr 0.0 --pseudo_type hard  --init_center st --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --patience 15 --net vgg --source Product --target Art --method cc --batchsize 64  --ratio_t 0.5   --save_dir vgghome --dataset OfficeHome --datapath /data/vdd/yabin/data/OfficeHome

CUDA_VISIBLE_DEVICES=7,6,5,4 python main.py --num_labeled 1 --base_lr 0.01 --max_iters 10000  --filter_type all --lp_labeled st --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center st --thr 0.0 --pseudo_type hard  --init_center st --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --patience 15 --net vgg --source Art --target Product --method cc --batchsize 64  --ratio_t 0.5   --save_dir vgghome --dataset OfficeHome --datapath /data/vdd/yabin/data/OfficeHome

CUDA_VISIBLE_DEVICES=7,6,5,4 python main.py --num_labeled 1 --base_lr 0.01 --max_iters 10000  --filter_type all --lp_labeled st --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center st --thr 0.0 --pseudo_type hard  --init_center st --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --patience 15 --net vgg --source Art --target Clipart --method cc --batchsize 64  --ratio_t 0.5   --save_dir vgghome --dataset OfficeHome --datapath /data/vdd/yabin/data/OfficeHome

CUDA_VISIBLE_DEVICES=7,6,5,4 python main.py --num_labeled 1 --base_lr 0.01 --max_iters 10000  --filter_type all --lp_labeled st --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center st --thr 0.0 --pseudo_type hard  --init_center st --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --patience 15 --net vgg --source Art --target Real --method cc --batchsize 64  --ratio_t 0.5   --save_dir vgghome --dataset OfficeHome --datapath /data/vdd/yabin/data/OfficeHome

CUDA_VISIBLE_DEVICES=7,6,5,4 python main.py --num_labeled 1 --base_lr 0.01 --max_iters 10000  --filter_type all --lp_labeled st --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center st --thr 0.0 --pseudo_type hard  --init_center st --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --patience 15 --net vgg --source Clipart --target Real --method cc --batchsize 64  --ratio_t 0.5   --save_dir vgghome --dataset OfficeHome --datapath /data/vdd/yabin/data/OfficeHome

CUDA_VISIBLE_DEVICES=7,6,5,4 python main.py --num_labeled 1 --base_lr 0.01 --max_iters 10000  --filter_type all --lp_labeled st --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center st --thr 0.0 --pseudo_type hard  --init_center st --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --patience 15 --net vgg --source Clipart --target Art --method cc --batchsize 64  --ratio_t 0.5   --save_dir vgghome --dataset OfficeHome --datapath /data/vdd/yabin/data/OfficeHome

CUDA_VISIBLE_DEVICES=7,6,5,4 python main.py --num_labeled 1 --base_lr 0.01 --max_iters 10000  --filter_type all --lp_labeled st --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center st --thr 0.0 --pseudo_type hard  --init_center st --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --patience 15 --net vgg --source Clipart --target Product --method cc --batchsize 64  --ratio_t 0.5   --save_dir vgghome --dataset OfficeHome --datapath /data/vdd/yabin/data/OfficeHome







#### for appendices, visualization of the discrimination information.
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --target_selection ours  \
 --source_weight instance --mu 1  --transform_type mme --max_iters 5000 --pre_epoch 5 --filter_type fc --lp_labeled st --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --patience 15 --net resnet34 --source train --target validation --method da_discrimination --batchsize 1024  --ratio_t 0.5   --save_dir appendices --dataset visDA --datapath /data/vdd/yabin/data

CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --target_selection ours --resume /data/vdd/yabin/AuxSelftrain/davisda/1117_log_visDA_cc_da_resnet34_train2validation_3labeled_Filterall_thr0.0_swinstance/last.resume  \
 --source_weight instance --mu 1  --transform_type mme --max_iters 5000 --pre_epoch 5 --filter_type fc --lp_labeled st --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --patience 15 --net resnet34 --source train --target validation --method da_discrimination --batchsize 1024  --ratio_t 0.5   --save_dir appendices --dataset visDA --datapath /data/vdd/yabin/data

CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --target_selection ours --resume /data/vdd/yabin/AuxSelftrain/appendices/1121_log_visDA_dann_resnet34_train2validation_3labeled_Filterall_thr0.0_swinstance/last.resume  \
 --source_weight instance --mu 1  --transform_type mme --max_iters 5000 --pre_epoch 5 --filter_type fc --lp_labeled st --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --patience 15 --net resnet34 --source train --target validation --method da_discrimination --batchsize 1024  --ratio_t 0.5   --save_dir appendices --dataset visDA --datapath /data/vdd/yabin/data

### appendices, compare rand and ours.
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --target_selection ours  --saving  --source_weight instance --mu 7  --transform_type mme --max_iters 5000 --pre_epoch 5 --filter_type all --lp_labeled st --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --patience 15 --net resnet34 --source Real --target Clipart --method cc_da --batchsize 64  --ratio_t 0.5   --save_dir appendices --dataset OfficeHome --datapath /data1/domain_adaptation

CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --target_selection rand  --saving  --source_weight instance --mu 7  --transform_type mme --max_iters 5000 --pre_epoch 5 --filter_type all --lp_labeled st --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --patience 15 --net resnet34 --source Real --target Clipart --method cc_da --batchsize 64  --ratio_t 0.5   --save_dir appendices --dataset OfficeHome --datapath /data1/domain_adaptation



#### for figure plot
CUDA_VISIBLE_DEVICES=2 python main.py --target_selection ours --t_start 0.0 --t_end 5.0 --base_lr 0.001 --lr_schedule fix --wd 1e-4 --source_weight none --mu 7 --max_iters 10000 --pre_epoch 20  --filter_type fc --lp_labeled s --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --net 3layer  --method mnist_plot --batchsize 64  --ratio_t 0.5   --save_dir acc_score_a_dis --dataset mnist --datapath /data1/domain_adaptation

CUDA_VISIBLE_DEVICES=2 python main.py --target_selection ours --t_start 5.0 --t_end 10.0 --base_lr 0.001 --lr_schedule fix --wd 1e-4 --source_weight none --mu 7 --max_iters 10000 --pre_epoch 20  --filter_type fc --lp_labeled s --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --net 3layer  --method mnist_plot --batchsize 64  --ratio_t 0.5   --save_dir acc_score_a_dis --dataset mnist --datapath /data1/domain_adaptation

CUDA_VISIBLE_DEVICES=2 python main.py --target_selection ours --t_start 10.0 --t_end 15.0 --base_lr 0.001 --lr_schedule fix --wd 1e-4 --source_weight none --mu 7 --max_iters 10000 --pre_epoch 20  --filter_type fc --lp_labeled s --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --net 3layer  --method mnist_plot --batchsize 64  --ratio_t 0.5   --save_dir acc_score_a_dis --dataset mnist --datapath /data1/domain_adaptation

CUDA_VISIBLE_DEVICES=2 python main.py --target_selection ours --t_start 15.0 --t_end 20.0 --base_lr 0.001 --lr_schedule fix --wd 1e-4 --source_weight none --mu 7 --max_iters 10000 --pre_epoch 20  --filter_type fc --lp_labeled s --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --net 3layer  --method mnist_plot --batchsize 64  --ratio_t 0.5   --save_dir acc_score_a_dis --dataset mnist --datapath /data1/domain_adaptation

CUDA_VISIBLE_DEVICES=2 python main.py --target_selection ours --t_start 20.0 --t_end 25.0 --base_lr 0.001 --lr_schedule fix --wd 1e-4 --source_weight none --mu 7 --max_iters 10000 --pre_epoch 20  --filter_type fc --lp_labeled s --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --net 3layer  --method mnist_plot --batchsize 64  --ratio_t 0.5   --save_dir acc_score_a_dis --dataset mnist --datapath /data1/domain_adaptation

CUDA_VISIBLE_DEVICES=2 python main.py --target_selection ours --t_start 25.0 --t_end 30.0 --base_lr 0.001 --lr_schedule fix --wd 1e-4 --source_weight none --mu 7 --max_iters 10000 --pre_epoch 20  --filter_type fc --lp_labeled s --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --net 3layer  --method mnist_plot --batchsize 64  --ratio_t 0.5   --save_dir acc_score_a_dis --dataset mnist --datapath /data1/domain_adaptation

CUDA_VISIBLE_DEVICES=2 python main.py --target_selection ours --t_start 30.0 --t_end 35.0 --base_lr 0.001 --lr_schedule fix --wd 1e-4 --source_weight none --mu 7 --max_iters 10000 --pre_epoch 20  --filter_type fc --lp_labeled s --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --net 3layer  --method mnist_plot --batchsize 64  --ratio_t 0.5   --save_dir acc_score_a_dis --dataset mnist --datapath /data1/domain_adaptation

CUDA_VISIBLE_DEVICES=2 python main.py --target_selection ours --t_start 35.0 --t_end 40.0 --base_lr 0.001 --lr_schedule fix --wd 1e-4 --source_weight none --mu 7 --max_iters 10000 --pre_epoch 20  --filter_type fc --lp_labeled s --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --net 3layer  --method mnist_plot --batchsize 64  --ratio_t 0.5   --save_dir acc_score_a_dis --dataset mnist --datapath /data1/domain_adaptation

CUDA_VISIBLE_DEVICES=2 python main.py --target_selection ours --t_start 40.0 --t_end 45.0 --base_lr 0.001 --lr_schedule fix --wd 1e-4 --source_weight none --mu 7 --max_iters 10000 --pre_epoch 20  --filter_type fc --lp_labeled s --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --net 3layer  --method mnist_plot --batchsize 64  --ratio_t 0.5   --save_dir acc_score_a_dis --dataset mnist --datapath /data1/domain_adaptation

CUDA_VISIBLE_DEVICES=2 python main.py --target_selection ours --t_start 45.0 --t_end 50.0 --base_lr 0.001 --lr_schedule fix --wd 1e-4 --source_weight none --mu 7 --max_iters 10000 --pre_epoch 20  --filter_type fc --lp_labeled s --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --net 3layer  --method mnist_plot --batchsize 64  --ratio_t 0.5   --save_dir acc_score_a_dis --dataset mnist --datapath /data1/domain_adaptation

CUDA_VISIBLE_DEVICES=2 python main.py --target_selection ours --t_start 50.0 --t_end 55.0 --base_lr 0.001 --lr_schedule fix --wd 1e-4 --source_weight none --mu 7 --max_iters 10000 --pre_epoch 20  --filter_type fc --lp_labeled s --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --net 3layer  --method mnist_plot --batchsize 64  --ratio_t 0.5   --save_dir acc_score_a_dis --dataset mnist --datapath /data1/domain_adaptation

CUDA_VISIBLE_DEVICES=2 python main.py --target_selection ours --t_start 55.0 --t_end 60.0 --base_lr 0.001 --lr_schedule fix --wd 1e-4 --source_weight none --mu 7 --max_iters 10000 --pre_epoch 20  --filter_type fc --lp_labeled s --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --net 3layer  --method mnist_plot --batchsize 64  --ratio_t 0.5   --save_dir acc_score_a_dis --dataset mnist --datapath /data1/domain_adaptation



#CUDA_VISIBLE_DEVICES=0 python main.py --t_start 30.0 --base_lr 0.001 --lr_schedule fix --wd 1e-4 --source_weight none --mu 7 --max_iters 10000 --pre_epoch 20  --filter_type all --lp_labeled s --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --net 3layer  --method mnist --batchsize 64  --ratio_t 0.5   --save_dir swmnist --dataset mnist --datapath /data1/domain_adaptation
#
#CUDA_VISIBLE_DEVICES=0 python main.py --t_start 30.0 --base_lr 0.001 --lr_schedule fix --wd 1e-4 --source_weight instance --mu 7 --max_iters 10000 --pre_epoch 20  --filter_type all --lp_labeled s --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --net 3layer  --method mnist --batchsize 64  --ratio_t 0.5   --save_dir swmnist --dataset mnist --datapath /data1/domain_adaptation
#
#CUDA_VISIBLE_DEVICES=0 python main.py --t_start 30.0 --base_lr 0.001 --lr_schedule fix --wd 1e-4 --source_weight soft --mu 7 --max_iters 10000 --pre_epoch 20  --filter_type all --lp_labeled s --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --net 3layer  --method mnist --batchsize 64  --ratio_t 0.5   --save_dir swmnist --dataset mnist --datapath /data1/domain_adaptation
#
#
#CUDA_VISIBLE_DEVICES=0 python main.py --t_start 30.0 --base_lr 0.001 --lr_schedule fix --wd 1e-4 --source_weight none --mu 7 --max_iters 10000 --pre_epoch 20  --filter_type all --lp_labeled s --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --net 3layer  --method mnist --batchsize 64  --ratio_t 0.5   --save_dir swmnist --dataset mnist --datapath /data1/domain_adaptation
#
#CUDA_VISIBLE_DEVICES=0 python main.py --t_start 30.0 --base_lr 0.001 --lr_schedule fix --wd 1e-4 --source_weight instance --mu 7 --max_iters 10000 --pre_epoch 20  --filter_type all --lp_labeled s --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --net 3layer  --method mnist --batchsize 64  --ratio_t 0.5   --save_dir swmnist --dataset mnist --datapath /data1/domain_adaptation
#
#CUDA_VISIBLE_DEVICES=0 python main.py --t_start 30.0 --base_lr 0.001 --lr_schedule fix --wd 1e-4 --source_weight soft --mu 7 --max_iters 10000 --pre_epoch 20  --filter_type all --lp_labeled s --lp_dis cos --lp_solver CG --lp_graphk 20 --lp_alpha 0.9 --init_center s --thr 0.0 --pseudo_type hard  --init_center s --pseudo_label_generator kmeans --feat_type_pseudo eval --pre_trained_G  --T 1.0 --weight 1.0 --num_workers 8 --mmd_lambda 1 --net 3layer  --method mnist --batchsize 64  --ratio_t 0.5   --save_dir swmnist --dataset mnist --datapath /data1/domain_adaptation
#
#



